'use strict'

const Scraper = require('./core/Scraper')
const links = [
	'',
	'/introduction/motivation',
	'/introduction/coreconcepts',
	'/introduction/threeprinciples',
	'/introduction/priorart',
	'/introduction/learningresources',
	'/introduction/ecosystem',
	'/introduction/examples',
	'/basics/actions',
	'/basics/reducers',
	'/basics/store',
	'/basics/dataflow',
	'/basics/usagewithreact',
	'/basics/exampletodolist',
	'/advanced/asyncactions',
	'/advanced/asyncflow',
	'/advanced/middleware',
	'/advanced/usagewithreactrouter',
	'/advanced/exampleredditapi',
	'/advanced/nextsteps',
	'/recipes/configuringyourstore',
	'/recipes/migratingtoredux',
	'/recipes/usingobjectspreadoperator',
	'/recipes/reducingboilerplate',
	'/recipes/serverrendering',
	'/recipes/writingtests',
	'/recipes/computingderiveddata',
	'/recipes/implementingundohistory',
	'/recipes/isolatingsubapps',
	'/recipes/structuringreducers',
	'/recipes/structuringreducers/prerequisiteconcepts',
	'/recipes/structuringreducers/basicreducerstructure',
	'/recipes/structuringreducers/splittingreducerlogic',
	'/recipes/structuringreducers/refactoringreducersexample',
	'/recipes/structuringreducers/usingcombinereducers',
	'/recipes/structuringreducers/beyondcombinereducers',
	'/recipes/structuringreducers/normalizingstateshape',
	'/recipes/structuringreducers/updatingnormalizeddata',
	'/recipes/structuringreducers/reusingreducerlogic',
	'/recipes/structuringreducers/immutableupdatepatterns',
	'/recipes/structuringreducers/initializingstate',
	'/recipes/usingimmutablejs',
	'/faq/general',
	'/faq/reducers',
	'/faq/organizingstate',
	'/faq/storesetup',
	'/faq/actions',
	'/faq/immutabledata',
	'/faq/codestructure',
	'/faq/performance',
	'/faq/designdecisions',
	'/faq/reactredux',
	'/faq/miscellaneous',
	'/troubleshooting',
	'/glossary',
	'/api',
	'/api/createstore',
	'/api/store',
	'/api/combinereducers',
	'/api/applymiddleware',
	'/api/bindactioncreators',
	'/api/compose'
]

const scraperInstance = new Scraper({
	title: 'Redux Documentation',
	baseUrl: 'https://redux.js.org',
	basePage: '',
	contentSelector: '._1vrwu4ou',
	addonCss: 'html,body { background: transparent; padding: 35px 20px !important } ._64y6qm { display: none; }',
	links,
	outputFile: 'reduxjs',
	openAfterCompile: true
}).run()
